name: "Documentation"

on: push

jobs:
  documentation:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate and commit table of content
        uses: technote-space/toc-generator@v2
        with:
          TARGET_PATHS: README.md
          TOC_TITLE: ""
          MAX_HEADER_LEVEL: 3
